### ISSUE TITLE
JS_webpack

### ISSUE THREAD

**Issue by TimofeiShpak** [thedreamwalker/dig_des_school#1]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/package.json#L17

нужно еще добавить команду для запуска devServer, чтобы можно было увидеть результат работы

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/js/index.js#L8

лучше это все (8-12 строки) обернуть в одну функцию, и вызывать одну функцию, 
позволит сделать код более гибким

а массив ['Проекты', 'Задачи', 'Пользователи'] - лучше вынести в константу

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/index.html#L11

добавил в дз пункт про то что в template должен быть элемент, чтобы не добавлять элементы в body, а в конкретный элемент

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/components/ListItem.js#L18

просьба эти строки (18-20) вынести в отдельную функцию, потому что ниже есть похожий функционал, чтобы не дублировать код

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/js/dropdown.js#L2

console.log нужно убрать

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/js/events.js#L6

console.log нужно убрать

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/js/dropdown.js#L25

лучше передавать объект, в котором будет название и класс (для кнопки удалить "dropdown__item_delite"), а то название кнопки может изменится, либо кнопок может стать больше с таким же классом

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/src/js/dropdown.js#L8

из-за этого элемента пропадает возможность взаимодействовать с другими элементами, нужно переделать

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/webpack.config.js#L49

просьба добавить alias в webpack.config.js, подробнее зачем указал в последнем пункте рекомендаций по написанию кода,
пример есть в моем коде

**Comment by TimofeiShpak** [comment]
просьба сделать эту иконку через svg

![image](https://github.com/thedreamwalker/dig_des_school/assets/60565887/fbb69e28-2655-4da2-ae46-7989aa43c117)

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/be2c0f7525dd4b42c6ee1a7dccebb4d814c9804a/.gitignore#L2

не уверен что все в этом писала ты, чужое лучше убрать, к тому же оно тут не нужно

**Comment by thedreamwalker** [comment]
все по замечаниям пофиксила

**Comment by TimofeiShpak** [comment]
не выполнен пункт задания "Для компонентов элемент списка задачи и элемент списка проектов при нажатии на кнопку “button/icon” должен появляться выпадающий список."

**Comment by TimofeiShpak** [comment]
https://github.com/thedreamwalker/dig_des_school/blob/02c7e0bf9dd4e2632775fd1260f732ab2d316f0c/src/css/item-style.scss#L22

просьба убрать комментарии тут и ниже

**Comment by thedreamwalker** [comment]
коммит с правками #https://github.com/thedreamwalker/dig_des_school/commit/9db096afacc75308f0197e96cf127cf892a8dd86

cенсей не бей! Загрузила на гитпэйджес чтобы не приходилось снова выгружать-собирать, кнопочки стали снова в форме [ссылка на деплой](https://thedreamwalker.github.io/dig_des_school/dist/)

**Comment by TimofeiShpak** [comment]
![image](https://github.com/thedreamwalker/dig_des_school/assets/60565887/d8b16f12-0dd5-4f94-89b6-9cf123dcf7c1)

16-й пункт рекомендаций по написанию кода, надо через svg добавлять иконку в кнопке

**Comment by thedreamwalker** [comment]
старалась ничего не сломать

коммит #https://github.com/thedreamwalker/dig_des_school/commit/bdf0a879a97fa519a48e0b3c3e4018f9c7ad117c

[деплой](https://thedreamwalker.github.io/dig_des_school/dist/)
